<?php

declare(strict_types=1);

namespace Accounting\Tests\Customers;

use PHPUnit\Framework\TestCase;
use Accounting\Database\DatabaseException;
use Accounting\Customers\{ CustomersDto, ICustomersRepository, CustomersRepository };

class CustomersRepositoryTest extends TestCase
{
    private $db;
    private $result;
    private array $input;
    private CustomersDto $dto;
    private ICustomersRepository $repository;

    protected function setUp(): void
    {
        $this->db = $this->createMock("Accounting\Database\IDatabase");
        $this->result = $this->createMock("Accounting\Database\IDatabaseResult");
        $this->input = [
            "id" => 6316,
            "name" => "Explain first while enough girl interview. Idea score capital. Against environmental choice in recognize.",
            "contact_person" => "Director south involve memory. Government stop quite send oil. Look community season range heavy both.",
            "email" => "stacey08@example.net",
            "phone" => "Reach add offer everybody his number. Fly edge matter read blood source cover.",
            "fax" => "Sea some hair star cold each. Successful seat heart sister language such capital. Indicate top than candidate.",
            "address" => "Bar some start. Air soon society past play resource miss. Nor affect guess stand work peace base wrong.",
        ];
        $this->dto = new CustomersDto($this->input);
        $this->repository = new CustomersRepository($this->db);
    }

    protected function tearDown(): void
    {
        unset($this->db);
        unset($this->result);
        unset($this->input);
        unset($this->dto);
        unset($this->repository);
    }

    public function testInsert_ReturnsFailedOnException(): void
    {
        $expected = -1;

        $this->db->method("prepare")
            ->will($this->throwException(new DatabaseException()));

        $actual = $this->repository->insert($this->dto);
        $this->assertEquals($expected, $actual);
    }

    public function testInsert_ReturnsId(): void
    {
        $expected = 4798;

        $sql = "INSERT INTO `Customers` (`name`, `contact_person`, `email`, `phone`, `fax`, `address`)
                VALUES (?, ?, ?, ?, ?, ?)";

        $this->db->expects($this->once())
            ->method("prepare")
            ->with($sql)
            ->willReturn($this->result);
        $this->result->expects($this->once())
            ->method("execute")
            ->with([
                $this->dto->name,
                $this->dto->contactPerson,
                $this->dto->email,
                $this->dto->phone,
                $this->dto->fax,
                $this->dto->address
            ]);
        $this->db->expects($this->once())
            ->method("lastInsertId")
            ->willReturn($expected);

        $actual = $this->repository->insert($this->dto);
        $this->assertEquals($expected, $actual);
    }

    public function testUpdate_ReturnsFailedOnException(): void
    {
        $expected = -1;

        $this->db->method("prepare")
            ->will($this->throwException(new DatabaseException()));

        $actual = $this->repository->update($this->dto);
        $this->assertEquals($expected, $actual);
    }

    public function testUpdate_ReturnsRowCount(): void
    {
        $expected = 7149;

        $sql = "UPDATE `Customers` SET `name` = ?, `contact_person` = ?, `email` = ?, `phone` = ?, `fax` = ?, `address` = ?
                WHERE `id` = ?";

        $this->db->expects($this->once())
            ->method("prepare")
            ->with($sql)
            ->willReturn($this->result);
        $this->result->expects($this->once())
            ->method("execute")
            ->with([
                $this->dto->name,
                $this->dto->contactPerson,
                $this->dto->email,
                $this->dto->phone,
                $this->dto->fax,
                $this->dto->address,
                $this->dto->id
            ]);
        $this->result->expects($this->once())
            ->method("rowCount")
            ->willReturn($expected);

        $actual = $this->repository->update($this->dto);
        $this->assertEquals($expected, $actual);
    }

    public function testGet_ReturnsEmptyOnException(): void
    {
        $id = 3029;

        $this->db->method("prepare")
            ->will($this->throwException(new DatabaseException()));

        $actual = $this->repository->get($id);
        $this->assertEmpty($actual);
    }

    public function testGet_ReturnsDto(): void
    {
        $id = 460;

        $sql = "SELECT `id`, `name`, `contact_person`, `email`, `phone`, `fax`, `address`
                FROM `Customers` WHERE `id` = ?";

        $this->db->expects($this->once())
            ->method("prepare")
            ->with($sql)
            ->willReturn($this->result);
        $this->result->expects($this->once())
            ->method("execute")
            ->with([$id]);
        $this->result->expects($this->once())
            ->method("fetchAll")
            ->willReturn([$this->input]);

        $actual = $this->repository->get($id);
        $this->assertEquals($this->dto, $actual);
    }

    public function testGetAll_ReturnsEmptyOnException(): void
    {
        $this->db->method("prepare")
            ->will($this->throwException(new DatabaseException()));

        $actual = $this->repository->getAll();
        $this->assertEmpty($actual);
    }

    public function testGetAll_ReturnsDtos(): void
    {
        $sql = "SELECT `id`, `name`, `contact_person`, `email`, `phone`, `fax`, `address`
                FROM `Customers`";

        $this->db->expects($this->once())
            ->method("prepare")
            ->with($sql)
            ->willReturn($this->result);
        $this->result->expects($this->once())
            ->method("execute");
        $this->result->expects($this->once())
            ->method("fetchAll")
            ->willReturn([$this->input]);

        $actual = $this->repository->getAll();
        $this->assertEquals([$this->dto], $actual);
    }

    public function testDelete_ReturnsFailedOnException(): void
    {
        $id = 6375;
        $expected = -1;

        $this->db->method("prepare")
            ->will($this->throwException(new DatabaseException()));

        $actual = $this->repository->delete($id);
        $this->assertEquals($expected, $actual);
    }

    public function testDelete_ReturnsRowCount(): void
    {
        $id = 3479;
        $expected = 1479;

        $sql = "DELETE FROM `Customers` WHERE `id` = ?";

        $this->db->expects($this->once())
            ->method("prepare")
            ->with($sql)
            ->willReturn($this->result);
        $this->result->expects($this->once())
            ->method("execute")
            ->with([$id]);
        $this->result->expects($this->once())
            ->method("rowCount")
            ->willReturn($expected);

        $actual = $this->repository->delete($id);
        $this->assertEquals($expected, $actual);
    }
}